// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM1mZjPoePjvtUt1P_ccXE61zCLLxOdZg',
    appId: '1:288234081894:web:ace63ed018cc2a5b1e67a7',
    messagingSenderId: '288234081894',
    projectId: 'baseadm-f1f63',
    authDomain: 'baseadm-f1f63.firebaseapp.com',
    storageBucket: 'baseadm-f1f63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwplonPs29aJESByawptZ130TAcf4qkL0',
    appId: '1:288234081894:android:3945756859a0742c1e67a7',
    messagingSenderId: '288234081894',
    projectId: 'baseadm-f1f63',
    storageBucket: 'baseadm-f1f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1LvuILf8iwrc1KURgcwBYIazaZm-o9s',
    appId: '1:288234081894:ios:296c38da1d8ef9431e67a7',
    messagingSenderId: '288234081894',
    projectId: 'baseadm-f1f63',
    storageBucket: 'baseadm-f1f63.appspot.com',
    iosClientId: '288234081894-rts9fjcij64bh9pmrij6al72rmalebs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseAdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR1LvuILf8iwrc1KURgcwBYIazaZm-o9s',
    appId: '1:288234081894:ios:296c38da1d8ef9431e67a7',
    messagingSenderId: '288234081894',
    projectId: 'baseadm-f1f63',
    storageBucket: 'baseadm-f1f63.appspot.com',
    iosClientId: '288234081894-rts9fjcij64bh9pmrij6al72rmalebs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseAdm',
  );
}
